### ISSUE TITLE
Bookmark repos or teams?

### ISSUE THREAD

**Issue by LordZardeck** [nicklayb/alfred-bitbucket#1]
I find having to always go through 2-3 steps to get where I want time consuming, would it be possible to bookmark teams and repos for quick access?

**Comment by nicklayb** [comment]
What do you think would be the best option for displaying them? Maybe showing them with teams, or adding an item "Bookmarks, where you can enter and seed the bookmarked repo?

I prefer the Bookmark "folder" as bookmarks can became huge. What do you think?

**Comment by LordZardeck** [comment]
Well the goal for me personally is to reduce the number of steps to get to a repo. So if you wanted to group bookmarks, i would say being able to access them from a keyword such as `bitmarks` or whatever, that would work for me. As far as adding them to the bookmarks, going through the current process and being able to take an action on a repo to add it to the bookmarks would work.

As for teams, it really doesn't make sense unless you are part of a LOT of teams to bookmark them, however, making one the default team could be very helpful. That way I could just use the `repo` keyword and by default it would use the team i've selected as default to search through.

**Comment by nicklayb** [comment]
I did a mistake, working on it
