### ISSUE TITLE
Use caching to speed up response time of workflow

### ISSUE THREAD

**Issue by LordZardeck** [nicklayb/alfred-bitbucket#18]
Currently you have to wait a little bit to get a response from bitbucket, even for the same query. It would be valuable to have a configurable cache lifetime, which could be implemented easily by adding the [maxAge](https://github.com/sindresorhus/alfy#maxage) option here: https://github.com/nicklayb/alfred-bitbucket/blob/master/utils.js#L3

It's also important that this cache lifetime be configurable (possibly an option to clear?) as I could have it cached for days at a time as my repos do not update often

**Comment by nicklayb** [comment]
@jonicious has add the feature using an env configurable delay. Hope it matches your need.
