### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sbilello** [nicklayb/alfred-bitbucket#20]
`3614 verbose unlock done using /Users/home/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
3615 timing stage:rollbackFailedOptional Completed in 142ms
3616 timing stage:runTopLevelLifecycles Completed in 6836ms
3617 verbose stack Error: alfred-bitbucket@1.3.0 postinstall: `alfy-init`
3617 verbose stack Exit status 1
3617 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
3617 verbose stack     at EventEmitter.emit (events.js:182:13)
3617 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3617 verbose stack     at ChildProcess.emit (events.js:182:13)
3617 verbose stack     at maybeClose (internal/child_process.js:961:16)
3617 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
3618 verbose pkgid alfred-bitbucket@1.3.0
3619 verbose cwd /Users/home/
3620 verbose Darwin 16.7.0
3621 verbose argv "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/bin/npm" "install" "--global" "alfred-bitbucket"
3622 verbose node v10.9.0
3623 verbose npm  v6.2.0
3624 error code ELIFECYCLE
3625 error errno 1
3626 error alfred-bitbucket@1.3.0 postinstall: `alfy-init`
3626 error Exit status 1
3627 error Failed at the alfred-bitbucket@1.3.0 postinstall script.
3627 error This is probably not a problem with npm. There is likely additional logging output above.`

`uname -a 
Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu 3789.73.11~1/RELEASE_X86_64 x86_64`

`npm --version
6.2.0`

**Comment by sbilello** [comment]
I retried with sudo and
`> alfred-bitbucket@1.3.0 install /usr/local/lib/node_modules/alfred-bitbucket
> node scripts/install.js

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'info.plist'
Emitted 'error' event at:
    at WriteStream.onerror (_stream_readable.js:690:12)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:139:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-bitbucket@1.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-bitbucket@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/home/.npm/_logs/2018-08-23T06_27_27_102Z-debug.log`

**Comment by nicklayb** [comment]
With sudo I'm sure you'll have issue. Since the user running the `info.example.plist` will be `root`, therefore you'll have a permission denied issue.

I also had this issue recently using node 10 version. Tested with the latest LTS version (8 and 12) did not caused any issue.

**Comment by nicklayb** [comment]
I'm closing this, everything should be fine using either an LTS or 14 version of node. Reopen if you still have issues
