### ISSUE TITLE
Keys not accepted

### ISSUE THREAD

**Issue by vanhumbeecka** [nicklayb/alfred-bitbucket#23]
When using the command `bit` or any other command, the script goes into error, and I'm out of the bitbucket-flow.
I've enabled debugging, en here is a screenshot where things go wrong:
![err](https://user-images.githubusercontent.com/4650078/71574587-aa3b9700-2ae9-11ea-9dad-f6e460040777.png)

The key + secret both shows up in the debug console, only it doesn't seem to work for some unclear reason.

Nice to know:
- I've added the client key and secret through alfred's configuration setting (so NOT the plist option)

Please advice. Thanks!

**Comment by royduin** [comment]
I've the same issue, did you fix it @vanhumbeecka?

**Comment by vanhumbeecka** [comment]
Nope not yet..

**Comment by nicklayb** [comment]
Sorry, I was out for holidays, I’ll try to check this week. I notice that I had a probleme when I call the bit the first time, after that it usually works.

**Comment by nicklayb** [comment]
Can you give it a try now using `1.4.2`? The fix might look stupid but as far as I understand, Alfred interprets the stdout of the afly package, so a lost `console.log` might break it completely.

**Comment by royduin** [comment]
The error is gone but it doesn't return any results.
```
[16:13:58.446] BitBucket[Script Filter] Queuing argument ''
[16:13:59.447] BitBucket[Script Filter] Queuing argument 't'
[16:13:59.545] BitBucket[Script Filter] Script with argv '' finished
[16:14:00.029] BitBucket[Script Filter] Queuing argument 'te'
[16:14:00.439] BitBucket[Script Filter] Queuing argument 'tes'
[16:14:00.670] BitBucket[Script Filter] Script with argv 't' finished
[16:14:00.733] BitBucket[Script Filter] Queuing argument 'test'
[16:14:01.779] BitBucket[Script Filter] Script with argv 'tes' finished
[16:14:02.879] BitBucket[Script Filter] Script with argv 'test' finished
```

**Comment by nicklayb** [comment]
Which command are you running? The bit command, for instance, is browsing through teams first

**Comment by royduin** [comment]
Tried `bit` and `repo` but both do not return anything in Alfred.

**Comment by nicklayb** [comment]
What permissions did you set to your Bitbucket key? Make sure that you have at least those

<img width="586" alt="image" src="https://user-images.githubusercontent.com/15114240/72623638-8662b880-3913-11ea-87b4-225cc2517195.png">

I will be looking forward to adding descriptive error messages when something fails.

Just to be sure, your `node` version is ?

**Comment by royduin** [comment]
Jup, got those permissions. I was running Node `v10.15.3` but just updated to `v12.14.1` with the same problem. Where to find or how to get any extra debug information?

**Comment by nicklayb** [comment]
Bitbucket seems to have a better way to support that using App passwords. I just did a clean install of version 1.5.1 using app passwords and everything worked fine, would you mind give it a try? Setup using app passwords are in the readme

**Comment by royduin** [comment]
Nice! It's finally working, thank you! 💯
