### ISSUE TITLE
Latest update is broken

### ISSUE THREAD

**Issue by LordZardeck** [nicklayb/alfred-bitbucket#8]
So the latest update broke opening repositories, in addition, the bookmark capabilities do not work. Shift+Enter does the same actions as just Enter

**Comment by nicklayb** [comment]
Are you sure you're at the latest update? I'm using it in both my office mac and my MacBook and everything is fine

**Comment by LordZardeck** [comment]
@nicklayb: Is this the latest? If not, NPM isn't up to date
![](http://take.ms/33345)
![](http://take.ms/NUFcL)

**Comment by nicklayb** [comment]
Yes it's the latest... When you say "the bookmark capabilities" can you detail a bit what's going on? Do you mean on bookmarking repo or setting default user?

**Comment by LordZardeck** [comment]
Here's a GIF of it not working. I can't set any bookmarks, and trying to open a repository gives me a broken link: 

![screencast 2017-07-31 14-07-45](https://user-images.githubusercontent.com/1145989/28794363-b51d7ee0-75fb-11e7-9a9a-d246cd2de868.gif)

**Comment by nicklayb** [comment]
Can you give me the good and the bad link so I can check with the code where mistakes could have been placed?

**Comment by LordZardeck** [comment]
Good: https://bitbucket.org/LordZardeck/procure-test
Bad: https://bitbucket.org/LordZardeck/LordZardeck/procure-test

**Comment by nicklayb** [comment]
I think you `info.plist` is not updated to the latest version. The link is not supposed to include your team name twice, but I did had this problem while I was writing the update. Can you screenshot me what does your workflow looks like in alfred?

**Comment by LordZardeck** [comment]
![](http://take.ms/24EXe)

**Comment by nicklayb** [comment]
I would first ask you to completely remove it `npm remove -g alfred-bitbucket` and then open alfred workflows dans delete then, re install it `npm install -g alfred-bitbucket`

Can't tell what's happening, when you're going into "Bookmarks" it should show you "No bookmarks" or all your bookmarks.

I may add a `bitreset` option which clears the bookmarks and the default username to do a "clean" refresh

**Comment by LordZardeck** [comment]
Nice, yeah, removing it and re-installing it worked. Might need to figure out that issue though so updates work well.

**Comment by nicklayb** [comment]
Glad to hear that! Maybe I should drop the old `info.plist` on each update and recopy the new one so I'm sure it's the newest one
