### ISSUE TITLE
Bookmarks sort at top?

### ISSUE THREAD

**Issue by LordZardeck** [nicklayb/alfred-bitbucket#9]
In my opinion, it would be good UX to have bookmarks always sorted at the top of a list.

**Comment by nicklayb** [comment]
Do you mean bookmarks sorted ascending, or always have the "Bookmarks" link in every action?

**Comment by LordZardeck** [comment]
Bookmarks sorted ascending, so that if they match the filter (or if there's no filter), any items in a list (teams or repos) that happen to be bookmarked would show up at the top

**Comment by nicklayb** [comment]
Oh right I understand, in repos, list should started with bookmarked repos, right? Maybe great, repos are actually sorted by their updated_at timestamps.

**Comment by LordZardeck** [comment]
Yeah, and actually, that's a really good idea too if you have access to the `updated_at` time stamp, that way you get the most relevant ones.

**Comment by nicklayb** [comment]
Resolve in #11
